

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: podinfo4
  namespace: default
spec:
  description: A secured release of podinfo
  package:
    repository: quay.io/kubodoc/packages/podinfo
    tag: 6.7.1-p04
    interval: 30m
  parameters:
    tls: true
    host: podinfo4
