

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: redis3
  namespace: default
spec:
  package:
    repository: quay.io/kubodoc/packages/redis
    tag: 20.6.1-p01
    interval: 30m
  parameters:
    ui:
      host: redis1
  moduleOverrides:
    - module: noname
      specPatch:
        releaseName: redis-engine
    - module: ui
      specPatch:
        values:
          redis:
            host: redis-engine-master
