

---
apiVersion: kubocd.kubotal.io/v1alpha1
kind: Release
metadata:
  name: redis1
  namespace: default
spec:
  package:
    repository: quay.io/kubodoc/packages/redis
    tag: 20.6.1-p01
  parameters:
    ui:
      host: redis1